### PR TITLE
feat: append name to codestar notification rule to allow creating a unique name

### PR DESCRIPTION
**Pull request by joe-niland**
- to allow multiple notifications module instances to be attached to the same codepipeline

### CODE REVIEW

**Comment by joe-niland** [comment]
@kjagiello edits by maintainers allowed

**Comment by joe-niland** [comment]
Hi @kjagiello friendly reminder to try the workflows again on this one

**Comment by joe-niland** [comment]
@kjagiello bump :)

**Review by kjagiello — APPROVED** [review]

**Comment by kjagiello** [comment]
Sorry for the long wait. Pushed the fixes now and everything seems to be working fine again now 👍 Thanks for your contribution!

**Comment by joe-niland** [comment]
Great, thanks @kjagiello !

**Pull request merged**
