### PR TITLE
added possibility to tag created resources

### PR DESCRIPTION
**Pull request by balihb**
added possibility to tag created resource (important for billing tags)
also rewrote policy multi line strings into policy documents

### CODE REVIEW

**Comment by kjagiello** [comment]
Thanks! Great job and nice seeing some improvements to the policies as well. Had it on my roadmap for very long time now. The CI issues does not seem to be related to your changes, so let me figure it out once I have some time and we'll get your PR merged in then.

**Comment by balihb** [comment]
it is ok now. the 0.6.0 version of the cloudposse labeling module only support 0.13 and up. so I returned it to 0.5.0

**Comment by kjagiello** [comment]
Awesome! Run a quick E2E test and everything looks fine. Thank you for your contribution!

**Review by kjagiello — APPROVED** [review]

**Comment by kjagiello** [comment]
Released it in v1.1.3.

**Pull request merged**
